addSbtPlugin("com.typesafe.play" % "sbt-plugin"            % "2.6.15")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"         % "1.5.1")
addSbtPlugin("org.scalastyle"   %% "scalastyle-sbt-plugin" % "1.0.0")
addSbtPlugin("com.typesafe.sbt"  % "sbt-native-packager"   % "1.3.4")
addSbtPlugin("org.foundweekends" % "sbt-bintray"           % "0.5.4")
addSbtPlugin("com.github.gseitz" %  "sbt-release"          % "1.0.8")
//addSbtPlugin("com.heroku"        % "sbt-heroku"            % "1.0.1")
